language: c
sudo: false
dist: trusty
os:
  - linux
  - osx
env:
  matrix:
    - ARCH=x86
    - ARCH=x86-64
addons:
  apt:
    packages:
      # Compile x86 on x86-64
      - gcc-multilib
      # git describe, etc
      - git
      # sbcl
      - sbcl
before_install:
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install sbcl; fi"
script:
  # gen-version.sh will use git describe. Travis only pulls with --depth 50.
  - git fetch --unshallow
  - ./make.sh "--xc-host=sbcl --noinform --end-runtime-options --no-sysinit --no-userinit --noprint --disable-debugger --end-toplevel-options" "--arch=$ARCH"